### ISSUE TITLE
Can't login with Twitter.

### ISSUE THREAD

**Issue by supernintendo** [kiding/beotsmusic#16]
Attempting to log into Beats Music with Twitter OAuth opens the login page / "Authorize an application" in your default browser. After authenticating, on the "redirect back to application" step you are redirected to a blank browser page. A possible fix is to open the Twitter login inside the app's WebView rather than in your default browser.

This occurs with the following browsers set as your "default browser":
Chrome 39.0.2171
Firefox 34.0.5
Safari 8.0.2

**Comment by kiding** [comment]
Could you check if Login with Facebook doesn't work for you either? PopupController.m:isLoginUrl should decide the policy - I wonder if that part has a problem, or something on the Twitter side has changed. I'm currently on a trip, I'll look into it as soon as I get back to my laptop.
