### ISSUE TITLE
Music playback fails when window is closed

### ISSUE THREAD

**Issue by Kyahx** [kiding/beotsmusic#17]
Using version 0.5 (latest as of 01/30/15)

Music playback will end after the current song if the window is closed.  In order for it to proceed to the next song the window has to be either open or minimized.  In previous version I was able to close the window and just leave BeotsMusic running in the dock.

**Comment by kiding** [comment]
An update to address this issue will be released soon. Thanks for reporting!

**Comment by kiding** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1336881/5978831/187ff106-a8e6-11e4-8bee-a9c8143c46c2.png)
Released! :dancer:
