### ISSUE TITLE
Primitive AppleScript Support for Playback Control

### ISSUE THREAD

**Issue by Plazmotech** [kiding/beotsmusic#19]
I was wondering if it's possible to add a menu-bar item for play/pause/skip? This would make integration with AppleScript so much easier, and would add a world of difference to my experience (in particular being able to control it with my phone).

**Comment by kiding** [comment]
Hey, thanks for making an issue!

That would be cool, but in that sense would _AppleScript_ support be much better? `tell application BeotsMusic to play` or some functions similar to _iTunes_ I guess.

**Comment by Plazmotech** [comment]
Yes, exactly! That would drastically enhance my experience. I use Alfred Remote, and I'd be able to attach simple AppleScript to allow full integration of BeotsMusic to my phone. Also I originally suggested menu-bar items because looking through the AppDelegate it seemed easier to implement. (I have no experience with designing apps besides SpriteKit for games)

**Comment by Plazmotech** [comment]
Fantastic! Now I just wait for the update. Thank you!

**Comment by kiding** [comment]
Released! :dancer:
